### PR TITLE
fix xss issue

### PR DESCRIPTION
**Pull request by patrickkettner**
currently the site has an xss issue

`http://modernizr.com/download/#-`

changing the bare selector to a `.find` off of the document itself fixes it.

### CODE REVIEW

**Comment by mathiasbynens** [comment]
Good catch @patrickkettner!

For the record, the “standardized” way to avoid these issues is to use [the `CSS.escape` method as defined in CSSOM](http://mths.be/cssescape) whenever you’re dynamically building a selector.

So instead of:

``` js
$('input[value="'+selections[i]+'"]').attr('checked', 'checked');
```

→

``` js
$('input[value="' + CSS.escape(selections[i]) + '"]').prop('checked', true);
```

**Comment by patrickkettner** [comment]
ah, thanks @mathiasbynens. a fountain of knowledge, as ever.

is that actually shipping anywhere (outside of polyfillable browsers)?

**Comment by mathiasbynens** [comment]
Not yet AFAIK, so your patch is definitely cleaner at the moment! :)

#### `CSS.escape` bug tickets
- Chromium/Chrome/Opera: https://code.google.com/p/chromium/issues/detail?id=331218
- Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=955860
- Internet Explorer: https://connect.microsoft.com/IE/feedback/details/812587
- WebKit/Safari: https://bugs.webkit.org/show_bug.cgi?id=126337

**Comment by patrickkettner** [comment]
[don't forget IE](https://connect.microsoft.com/ie)

:D

**Comment by patrickkettner** [comment]
you are a machine, mi amigo

**Pull request merged**
