### PR TITLE
Add beta flag to main site.

### PR DESCRIPTION
**Pull request by ryanseddon**
I know you've tagged alpha releases, so I can change it to alpha if need be but I don't think we're far off doing a beta cut.

screen shot 2015-03-01 at 4 27 12 pm

### CODE REVIEW

**Comment by patrickkettner** [comment]
whats the new styles for?

**Comment by ryanseddon** [comment]
Probably hard to tell but I copied @stucox styles he did on the banner for v3 site https://github.com/Modernizr/v3.modernizr.com/commit/b7f0dba81e7595a2e4e2c89dcbec04c15fb84473#diff-361ef4eb9c8a7b86b8df3dc7b401d1ddR1154

**Comment by patrickkettner** [comment]
ah - beaut. :+1:

**Comment by ryanseddon** [comment]
Happy with it saying beta even though we have alpha cuts?

**Comment by patrickkettner** [comment]
potato, potato far as I am concerned. "beta' branding should be coming within a week or two. The only reason it is in "alpha" is because of it being leaked on npm early, and me not wanting to have it be beta before all the compat code landed.

**Comment by patrickkettner** [comment]
just realized this should probably link to http://v3.modernizr.com/download,
rather than the main page.

On Sun, Mar 1, 2015 at 12:34 AM, Ryan Seddon notifications@github.com
wrote:

> Merged #53 https://github.com/Modernizr/modernizr.com/pull/53.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Modernizr/modernizr.com/pull/53#event-243897785.

## 

patrick

**Comment by ryanseddon** [comment]
yep realised that too, fixing now

**Comment by ryanseddon** [comment]
Fixed here 867cbfc2f80b9aebb79ce2fd67bc2bbcbf0c82c6

**Pull request merged**
