### PR TITLE
[dogfood] Update modernizr.com's version to 2.5.3.

### LINKED ISSUE #10: modernizr.com needs to update its version of modernizr
Modernizr._version === "2.0.6"

:(

### PR DESCRIPTION
**Pull request by bobthecow**
Closes #10 

Note that iepp is now printshiv, and Respond.js has moved to a separate file since Modernizr is no longer built with Respond.js.

### CODE REVIEW

**Comment by paulirish** [comment]
Nice!! thanks

though the modernizr filename uses `1.6` instad of `2.5.3`.. Can you bump that?

**Comment by bobthecow** [comment]
@paulirish I thought the same thing, but that number seems to be an asset version, not a modernizr version. See https://github.com/Modernizr/modernizr.com/blob/gh-pages/i/js/modernizr.com-custom-1.2.js etc.

**Comment by paulirish** [comment]
true. I think we were just being lazy, tbh.

but since its actually modernizr.js plus some siteinit i can see why
something like 2.5.3_1.x would make more sense.

no bigs.

**Comment by paulirish** [comment]
merged.

**Comment by bobthecow** [comment]
Thank you!

**Comment by KuraFire** [comment]
We can switch over to that proposed versioning/naming scheme (2.5.3_1, etc.) at the next major overhaul, with 3.0.

**Comment by bobthecow** [comment]
`2.5.3-1` fits better with semver(ish) numbering.

**Pull request merged**
