### PR TITLE
Fix the build URL for some non-core detects

### PR DESCRIPTION
**Pull request by eeabed**
The Build URL doesn't work for some detects that have dashes in their input values. This includes network-xhr2, blob-constrctor and others. If you generate modernizr with network-xhr2 support, and then try to visit the Build URL included in the modernize file, the network-xhr2 detect is not selected as it should.

The same happens for a few other detects. All of them fixed.

### CODE REVIEW

**Comment by SlexAxton** [comment]
You're a saint.

**Comment by SlexAxton** [comment]
After pulling that, I realized I once hit a bug where the checkboxes were selected but I had messed with the values and the actual code wasn't being included. Did you check both the checkbox and that the test was actually added? (I'm sure you did, I am just being diligent!)

**Comment by SlexAxton** [comment]
Nm. Just tested. Seems to work! Thanks!

**Comment by eeabed** [comment]
Thanks for merging.

**Comment by paulirish** [comment]
@eeabed thank you much!

**Comment by eeabed** [comment]
@paulirish @SlexAxton  Thank you guys for the awesome Modernizr project.

**Pull request merged**
